---
title: "Introduction to baytaAAR"
author: "Nils Müller-Scheeßel"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to baytaAAR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction

`baytaAAR` implements latent trait analysis within a Bayesian Markov Chain Monte Carlo (MCMC) framework.

`baytaAAR` has been introduced and tested in the paper ###.


## JAGS vs. nimble vs. stan

We use both JAGS and nimble. Nimble uses a derivate of the JAGS/BUGS language, so that the models can be used interchangeably with only little modifications (https://r-nimble.org/manual/cha-writing-models.html#sec:supp-feat-bugs). Still, JAGS and nimble are conceptually quite different. While it is theoretically possible to extend the functionality of JAGS by custom functions, this process is far from self-evident and presupposes advanced programming skills. Therefore, the available functions and samplers have to be taken as their are. On contrast, nimble offers a mind-boggling suite of customizing possibilities. This is especially true for the samplers used for even individual nodes. We tried our best to find the best model parameters, with, however, only limited success. We found that the default samplers of nimble exhibit poorer mixing than those of JAGS and thus need longer chains to reach the same ESS. Roughly the same number of steps are only reached when nimble is forced to fall back on the Gibbs ('slice') sampler. This comes with higher computation costs and slower chains but this disadvantage is more than outweighed but the smaller number of steps necessary to reach ESS defined as quality threshold (10,000). Overall, however, we observed that the same model with the same data takes longer to run on nimble than it does on JAGS.

Therefore, for univariate cases, we propose to use JAGS, while for multivariate applications with multinormal likelihood function, nimble is the only alternative.

We interface JAGS with a wrapper function which in turn relies on runjags (##) for running JAGS. nimble is a package in its own right (##).

We do not use stan (##) which is probably currently the most popular choice when it comes to work with Bayesian models in R. The reason for this is two-fold: Firstly, stan is much more restrictive in relation to unobserved nodes. While JAGS and nimble simply treat those as parameters to be estimated, they have to be explicitly declared in stan. Secondly, and more importantly, stan does not provide the interval-distribution (dinterval) which is instrumental to our application because only with the dinterval-distribution it is possible to implement the multivariate model.


## Gompertz distribution with JAGS and nimble

Central to baytaAAR is the Gompertz distribution, named after the British mathematican W. Gompertz who first presented it in 1825. Despite or even because of its simplicity, it is still widely applied. Instrumental for baytaAAR is the strong empiric correlation between its two parameters alpha and beta which makes it possible to reformulate it as essentially a one-parameter-distribution that still captures human mortality adequately. The parameter beta is estimated from the observed data, thus at the same time defining the overall level of mortality of the respective population and also narrowing down the age range of the individuals.

The Gompertz distribution is implemented in JAGS with the so-called "ones"-trick, which is a simple, convenient way to implement custom distributions. Nimble, however, allows to add custom functions as nimble functions that are therefore compiled at runtime. Because of this difference in implementation, the same data will lead to slightly different estimates of the alpha and beta parameters when run with the JAGS- or the nimble-models.

Nimble truncates the probability distribution.


## Parallel processing and number of chains

On modern hardware with usually more than one core, parallel processing is very useful as it cuts down time significantly. In a normal case, you would use as many cores as you specify chains. The default for JAGS and nimble is three chains. More chains can help in reaching quality criteria like psrf faster. However, it also increases the size of the MCMC samples. Therefore, and following Kruschke, we control the number of saved runs by dividing numsavedruns by the number of chains. So, increasing the number of chains will automatically shorten the number of saved runs which will usually lead to poorer mixing. In this respect, we made the observation for our model that a higher number of chains does not outweigh the disadvantage of shorter chains. Therefore, we actually do not advise to increase the number of chains.


### Parallel processing in JAGS

Parallel processing in JAGS is straightforward. In bay.ta.jags, you specify the mode of operation with the parameter "method". "rjags" equals single-core-processing, and with "rjparallel" and "parallel", you invoke parallel processing. "parallel" is the usual choice as it gives feedback during processing.


### Parallel processing in nimble

Parallel processing in nimble is much more complicated. The handbook gives a general account of the necessary steps (https://r-nimble.org/examples/parallelizing_NIMBLE.html). For a package like ours, there is the additional difficulty that we provide custom functions which have to be supplied in the environment of each cluster. However, simply copying the functions to the global environment would be unacceptable behaviour of a package.

In the end, we hope that we succeeded to make parallel processing with nimble as unintrusive as possible by providing a wrapper function "bay.ta.nimble" which takes care of the different modes of operation. Please note, though, that you will get no feedback during running the function in parallel. Therefore, it is good practice to start with a low number of steps and see how long these take, interpolate the number of necessary steps from the quality measures (especially ESS) and change the settings accordingly.

---
