---
title: "Computation framework"
output: rmarkdown::html_vignette
bibliography: ../inst/REFERENCES.bib
vignette: >
  %\VignetteIndexEntry{Computation framework}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## JAGS vs. NIMBLE vs. stan

We use both JAGS [@plummer_2003] and NIMBLE [@valpine_et_al_2017]. NIMBLE uses a derivate of the [JAGS/BUGS language](https://r-nimble.org/manual/cha-writing-models.html#sec:supp-feat-bugs), so that the models can be used interchangeably with only little modifications. Still, JAGS and NIMBLE are conceptually quite different. While it is theoretically possible to extend the functionality of JAGS by custom functions, this process is far from self-evident and presupposes advanced programming skills. Therefore, the available functions and samplers have to be taken as their are. On contrast, NIMBLE offers a great suite of customizing possibilities. This is especially true for the samplers used for even individual nodes. We tried our best to find the best model parameters, with, however, only limited success. We found that the default samplers of NIMBLE exhibit poorer mixing than those of JAGS and thus need longer chains to reach the same level in terms of quality measures. Overall, we observed that the same model with the same data takes longer to run on NIMBLE than it does on JAGS. Additionally, NIMBLE is less stable than JAGS, especially in the multicore setup.

For the reasonse named above, we propose to use JAGS for the univariate cases and cases with multiple normal likelihood, while for multivariate applications with multinormal likelihood function, NIMBLE is the only alternative.

Despite the fact that the models of JAGS and NIMBLE are almost identical, the differences are subtle enough so that the same data and the same parameter will produces slightly different results. This is because JAGS and NIMBLE use different samplers and the way the ordinal thresholds are ordered works differently.

We interface JAGS with a wrapper function which in turn relies on `runjags` [@derwood_2016] for running JAGS. NIMBLE is a package in its own right [@valpine_et_al_2017]. The processing of the chains is done with the `coda` package [@plummer_et_al_2006]. For the further analysis, `baytaAAR` provides custom functions but in the vignettes we also show how to analyse the data with the packages `posterior` [@buerkner_et_al_2026] and `tidybayes` [@kay_2024].

We do not use [`stan`](https://mc-stan.org) which is probably currently the most popular choice when it comes to working with Bayesian models in R. The reason for this is two-fold: Firstly, `stan` is much more restrictive in relation to unobserved nodes. While JAGS and NIMBLE simply treat those as parameters to be estimated, they have to be explicitly declared in `stan`. Secondly, and more importantly, `stan` does not provide the interval-distribution (`dinterval`) which is instrumental to our application because only with the `dinterval`-distribution it is possible to implement the multivariate model.



## Parallel processing and number of chains

On modern hardware with usually more than one core, parallel processing is very useful as it cuts down time significantly. In a normal case, you would use as many cores as you specify chains. The default for JAGS and NIMBLE is three chains. More chains can help in reaching quality criteria like `PSRF` faster. However, it also increases the size of the MCMC samples so that post-processing in the end becomes a question of available memory. Therefore, and following Kruschke, we control the number of saved iterations by dividing `numSavedSteps` by the number of chains. So, increasing the number of chains will automatically shorten the number of saved iterations which will usually lead to poorer mixing. In this respect, we made the observation for our model that a higher number of chains does not outweigh the disadvantage of shorter chains. Therefore, we actually do not advise to increase the number of chains.

Parallel processing is straightforward. In `bay.ta`, you specify the mode of operation with the parameter `multicore` which can be `FALSE` (single-core-processing) or `TRUE` (parallel processing). This runs out-of-the-box with JAGS but parallel processing in NIMBLE is much more complicated. The [NIMBLE manual](https://r-nimble.org/examples/parallelizing_NIMBLE.html) gives a general account of the necessary steps. For a package like ours, there is the additional difficulty that we provide custom functions which have to be supplied in the environment of each cluster. However, simply copying the functions to the global environment would be unacceptable behaviour of a package. We use the R-package `parallel`, which is part of Basic R, for multi-core processing in NIMBLE.

In the end, we hope that we succeeded to make parallel processing with NIMBLE as unintrusive as possible by providing a wrapper function which takes care of the different modes of operation. Please note, though, that you will get no feedback during running your model in parallel. Therefore, it is good practice to start with a low number of steps and see how long these take, interpolate the number of necessary steps from the quality measures (especially `ESS`) and change the settings accordingly.

Generally, JAGS is very stable in parallel processing so except of the possible fact that your fans might start to spin, you will notice very little difference between single- and multicore-processing. For NIMBLE, this is unfortunately not always the case. Apart from the missing of any feedback, there is also the possibility of a memory leak. This makes the cores consume more and more memory until the machine becomes unusable and might eventually crash. Therefore, we would strongly advise to monitor the cores closely to see if their consumation of memory remains stable or steadily increases. If the latter is the case, the model should be stopped and the R-GUI should be restarted. Furthermore, it might be necessary to kill the processes manually in the monitoring software.

---

## References
