---
title: "JAGS vs NIMBLE"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{JAGS_vs_NIMBLE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## JAGS vs. NIMBLE vs. stan

We use both JAGS and NIMBLE. NIMBLE uses a derivate of the JAGS/BUGS language, so that the models can be used interchangeably with only little modifications (https://r-nimble.org/manual/cha-writing-models.html#sec:supp-feat-bugs). Still, JAGS and NIMBLE are conceptually quite different. While it is theoretically possible to extend the functionality of JAGS by custom functions, this process is far from self-evident and presupposes advanced programming skills. Therefore, the available functions and samplers have to be taken as their are. On contrast, NIMBLE offers a great suite of customizing possibilities. This is especially true for the samplers used for even individual nodes. We tried our best to find the best model parameters, with, however, only limited success. We found that the default samplers of NIMBLE exhibit poorer mixing than those of JAGS and thus need longer chains to reach the same ESS. Overall, we observed that the same model with the same data takes longer to run on NIMBLE than it does on JAGS.

Therefore, for univariate cases, we propose to use JAGS, while for multivariate applications with multinormal likelihood function, NIMBLE is the only alternative.

We interface JAGS with a wrapper function which in turn relies on runjags (##) for running JAGS. NIMBLE is a package in its own right (##).

We do not use stan (##) which is probably currently the most popular choice when it comes to work with Bayesian models in R. The reason for this is two-fold: Firstly, stan is much more restrictive in relation to unobserved nodes. While JAGS and NIMBLE simply treat those as parameters to be estimated, they have to be explicitly declared in stan. Secondly, and more importantly, stan does not provide the interval-distribution (dinterval) which is instrumental to our application because only with the dinterval-distribution it is possible to implement the multivariate model.
